name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    name: Test Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6','2.7', '3.0', '3.1', '3.2' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Lint  files
        run: bundle exec rake rubocop
      - name: Run tests
        run: bundle exec rake spec
      - name: Verify documentation is up to date
        run: bundle exec rake generate_cops_documentation
        env:
          CI: true
